name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    - run: pip install -r requirements.txt
    - run: npm ci
    - run: pip install pytest pytest-cov
    - run: pytest -q --cov=xhs_utils --cov=apis --cov-report=xml
